### ISSUE TITLE
[chore] add dependabot to keep deps uptodate

### ISSUE THREAD

**Issue by BeauBouchard** [free-ignorance/soothsaying#20]
### Description of changes

Add dependabot

### Acceptance Criteria

make a pr to add the `.github/dependabot.yml` with the default contents for an npm ecosystem like so: 

```yaml
version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
```
